# Uncomment the next line to define a global platform for your project
#platform :ios, '11.3'


target 'IDEHospital_Intake1_Team5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IDEHospital_Intake1_Team5
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SkyFloatingLabelTextField'
  pod 'SDWebImage'
  pod 'NVActivityIndicatorView'
  pod 'SwiftGen'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'PaginatedTableView'


end
